[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "termnetlog"
version = "0.2.0b1"
license = {file = "LICENSE"}
description = "Terminal net logger for amateur radio nets"
requires-python = ">=3.11"
dependencies = [
    "textual>=0.80",
    "httpx>=0.27",
    "platformdirs>=4",
    "tzdata>=2024.1",
    "tomlkit>=0.13.0",
]

[project.optional-dependencies]
dev = ["pytest>=8", "pytest-asyncio>=0.23", "adif-io>=0.6.1", "textual-dev"]

[project.scripts]
termnetlog = "termnetlog.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
termnetlog = ["tui/*.tcss"]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
